<?xml version='1.1' encoding='UTF-8'?>
<Tag plugin="workflow-support@804.vba10a18a1476">
  <node class="cps.n.StepAtomNode" plugin="workflow-cps@2648.va9433432b33c">
    <parentIds>
      <string>12</string>
    </parentIds>
    <id>13</id>
    <descriptorId>org.jenkinsci.plugins.workflow.steps.durable_task.ShellStep</descriptorId>
  </node>
  <actions>
    <cps.a.ArgumentsActionImpl plugin="workflow-cps@2648.va9433432b33c">
      <arguments>
        <entry>
          <string>script</string>
          <string>
        docker run             --rm             --net host             -e SONAR_HOST_URL=&quot;http://35.247.164.137:9000&quot;             -v ${PWD}:/usr/src              sonarsource/sonar-scanner-cli             -Dsonar.verbose=true             -Dsonar.host.url=http://35.247.164.137:9000             -Dsonar.projectName=sonarqube-test             -Dsonar.projectKey=sonarqube-test             -Dsonar.login=2aaca7485ae9a1b0eeec77e6a3a71c87cee7cfe8             -Dsonar.sources=.
         </string>
        </entry>
      </arguments>
      <sensitiveVariables/>
      <isUnmodifiedBySanitization>true</isUnmodifiedBySanitization>
    </cps.a.ArgumentsActionImpl>
    <wf.a.TimingAction plugin="workflow-api@1108.v57edf648f5d4">
      <startTime>1641453687897</startTime>
    </wf.a.TimingAction>
    <s.a.LogStorageAction/>
    <wf.a.ErrorAction plugin="workflow-api@1108.v57edf648f5d4">
      <error class="hudson.AbortException">
        <detailMessage>script returned exit code 1</detailMessage>
        <stackTrace>
          <trace>org.jenkinsci.plugins.workflow.steps.durable_task.DurableTaskStep$Execution.handleExit(DurableTaskStep.java:664)</trace>
          <trace>org.jenkinsci.plugins.workflow.steps.durable_task.DurableTaskStep$Execution.check(DurableTaskStep.java:610)</trace>
          <trace>org.jenkinsci.plugins.workflow.steps.durable_task.DurableTaskStep$Execution.run(DurableTaskStep.java:554)</trace>
          <trace>java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)</trace>
          <trace>java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)</trace>
          <trace>java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)</trace>
          <trace>java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)</trace>
          <trace>java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)</trace>
          <trace>java.base/java.lang.Thread.run(Thread.java:829)</trace>
        </stackTrace>
        <suppressedExceptions class="empty-list"/>
      </error>
    </wf.a.ErrorAction>
  </actions>
</Tag>